export const REQUEST_ARTICLE = 'REQUEST_ARTICLE';
export const RECEIVE_ARTICLE = 'RECEIVE_ARTICLE';

export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';

export const REQUEST_UPDATE_ARTICLE = 'REQUEST_UPDATE_ARTICLE';
export const UPDATED_ARTICLE = 'UPDATED_ARTICLE';
export const POST_UPDATED_ARTICLE = 'POST_UPDATED_ARTICLE';

export const REQUEST_REMOVE_ARTICLE = 'REQUEST_REMOVE_ARTICLE';
export const REMOVING_ANIMATION_ARTICLE = 'REMOVING_ANIMATION_ARTICLE';
export const REMOVED_ARTICLE = 'REMOVED_ARTICLE';

export const ERROR_FETCHING = 'ERROR_FETCHING';
